hideOverlays = "RELOADING"
rgbProgress = false
blockOverlay = false
miniRender = true
enableScissor = false
type = "PROGRESS"
reloadText = "Edit in config!"
resetResources = true
reInitScreen = true
removeOverlayAtEnd = true
earlyPackStatusSend = true
doubleLoad = "FORCE_LOAD"
animationSpeed = 1000.0
